### ISSUE TITLE
unable to use it

### ISSUE THREAD

**Issue by alihbuzaid** [FriendsOfFlarum/extension-generator#10]
I generate the ext and add it through composer 
but after enabling the ext {as is}
the forum stop to operate 
and it doesn't give any error !

**Comment by dsevillamartin** [comment]
I'm assuming you figured out that you have to build the JS dist file before being able to use it.

In case you think that perhaps the default dist file should be included, I think it stay the way it is because it makes sure the developer at least knows something of what they are doing 😛 

Perhaps we should add a notice right before the generator exists, though.
